name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.*"

jobs:
  prepare:
    name: Create draft release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Yes, this is the lazy way of doing it. Am I lazy? Yes.
      # - name: Create draft release
      #   #env:
      #     ##GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "### [Install guide](https://github.com/ethangreen-dev/lovely-injector?tab=readme-ov-file#manual-installation)" >> NOTE.md
      #     echo "|OS|Download|" >> NOTE.md
      #     echo "|--|--|" >> NOTE.md
      #     echo "|Windows|[lovely-x86_64-pc-windows-msvc.zip](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-x86_64-pc-windows-msvc.zip)|" >> NOTE.md
      #     echo "|Mac (Arm)|[lovely-aarch64-apple-darwin.tar.gz](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-aarch64-apple-darwin.tar.gz)|" >> NOTE.md
      #     echo "|Mac (x86)|[lovely-x86_64-apple-darwin.tar.gz](https://github.com/ethangreen-dev/lovely-injector/releases/download/${{ github.ref_name }}/lovely-x86_64-apple-darwin.tar.gz)|" >> NOTE.md

      #     gh release create ${{ github.ref_name }} \
      #     --title "${{ github.ref_name }}" \
      #     --draft  \
      #     --generate-notes \
      #     --notes-file NOTE.md \

  build-windows:
    needs: prepare
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --package lovely-win --release

      - name: Compress
        run: |
          cd ./target/${{ matrix.target }}/release/
          7z a "lovely-${{ matrix.target }}.zip" version.dll
          mv "lovely-${{ matrix.target }}.zip" ${{ github.workspace }}


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            lovely-${{ matrix.target }}.zip
      # - name: Submit build artifact
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: >-
      #     gh release upload ${{ github.ref_name }} lovely-${{ matrix.target }}.zip

  build-unix:
    needs: prepare
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-linux-android
          - armv7-linux-androideabi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}
      - name: Install Anroid ADK
        shell: bash
        run: |
          # Set an environment variable for convenience.
          ENV GRADLE_ROOT=/home/dev/opt/gradle

          RUN mkdir -p ${GRADLE_ROOT}
          RUN wget https://github.com/gradle/gradle-distributions/releases/download/v8.12.0/gradle-8.12-bin.zip -O gradle-8.12-bin.zip \
            && sha256sum gradle-8.12-bin.zip \
            && echo "7a00d51fb93147819aab76024feece20b6b84e420694101f276be952e08bef03  gradle-8.12-bin.zip" | sha256sum -c - \
            && unzip gradle-8.12-bin.zip -d ${GRADLE_ROOT} \
            && rm gradle-8.12-bin.zip

          # Add the relevant directories to the $PATH.
          ENV PATH=${PATH}:${GRADLE_ROOT}/gradle-8.12/bin
          # Set the ${ANDROID_HOME} variable, so that the tools can find our installation.
          # See https://developer.android.com/studio/command-line/variables#envar.
          ENV ANDROID_HOME=/home/dev/opt/android-sdk
          
          # Download and extract the command-line tools into ${ANDROID_HOME}.
          RUN mkdir -p ${ANDROID_HOME}
          RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip \
                  -O ${HOME}/commandlinetools-linux-11076708_latest.zip \
              && sha256sum commandlinetools-linux-11076708_latest.zip \
              && echo "2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258 commandlinetools-linux-11076708_latest.zip" | sha256sum -c - \
              && unzip commandlinetools-linux-11076708_latest.zip -d ${ANDROID_HOME}/cmdline-tools \
              && rm commandlinetools-linux-11076708_latest.zip
          
          # Add the relevant directories to the $PATH.
          ENV PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/cmdline-tools/bin:${ANDROID_HOME}/platform-tools
          
          echo yes~|sdkmanager --licenses
          RUN yes | sdkmanager --licenses \
              && sdkmanager --verbose \
                  "build-tools;34.0.0" \
                  "ndk;27.2.12479018" \
                  "platforms;android-35"
          ENV NDK_HOME=${ANDROID_HOME}/ndk/27.2.12479018
          echo "SDKROOT=${ANDROID_HOME}/ndk/27.2.12479018" >> $GITHUB_ENV


      # - name: Install Mac SDK
      #   run: |
      #     curl -L "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz" | tar -J -x -C /opt
      #     curl -L "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz" | tar -J -x -C /opt
      #     echo "SDKROOT=/opt/MacOSX11.3.sdk" >> $GITHUB_ENV

      - name: Install cargo-zigbuild
        run: |
          pip3 install cargo-zigbuild

      - name: Build
        run: cargo zigbuild --target ${{ matrix.target }} --package lovely-unix --release

      - name: Compress tar.gz
        run: |
          cp ./crates/lovely-unix/run_lovely_linux.sh ./target/${{ matrix.target }}/release/
          cd ./target/${{ matrix.target }}/release/
          tar czfv lovely-${{ matrix.target }}.tar.gz liblovely.so run_lovely_linux.sh
          mv "lovely-${{ matrix.target }}.tar.gz" ${{ github.workspace }}
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }} Build
          path: |
            lovely-${{ matrix.target }}.tar.gz

